name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: apt update
      run: sudo apt update
    - name: Install tools
      run: sudo apt install -y default-jdk maven
    - name: Build with Maven
      run: mvn -B package --file java/pom.xml
